version: '3.3'

services:
  db:
    image: mysql:5.5
    volumes:
      - "./mysql_data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shmup
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306