name: hiscores-api Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        env:
          CI: true
        with:
          java-version: 15
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      #- name: Run codacy-coverage-reporter
      #  uses: codacy/codacy-coverage-reporter-action@master
      #  with:
      #    project-token: ${{ secrets.CODACY_TOKEN }}
      - uses: actions/upload-artifact@v1
        with:
          name: de-sy-file
          path: target/
  push:
    name: Push Docker Image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: de-sy-file
          path: target/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          file: ./Dockerfile
          tags: jsmadja/hiscores:latest
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: jsmadja/hiscores
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
