# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: hiscores-api deploy

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

jobs:
  deploy:
    name: Deploy
  runs-on: ubuntu-latest
    steps:
      - name: Deploy hiscores
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          script: docker-compose pull && docker-compose down && docker-compose up -d
